services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'

  YoRus\BehatContext\FidryAliceFixturesContext:
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@fidry_alice_data_fixtures.loader.doctrine'
      - %kernel.project_dir%
      - "tests/Fixtures"

  YoRus\BehatContext\Domain\BehatStore: ~

  YoRus\BehatContext\Domain\Jwt\Configuration:
    arguments:
      $configuration: '%yorus_behat_context.jwt_login%'

  ##############################################################
  ##### Argument Resolvers
  ##############################################################
  YoRus\BehatContext\App\Resolver\BehatStoreResolver:
    arguments:
      $store: '@YoRus\BehatContext\Domain\BehatStore'
    tags: [ 'context.argument_resolver' ]

  YoRus\BehatContext\App\Resolver\JwtConfigurationResolver:
    arguments:
      $jwtConfiguration: '@YoRus\BehatContext\Domain\Jwt\Configuration'
    tags: [ 'context.argument_resolver' ]

